// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import AsyncStorage from '@react-native-async-storage/async-storage';

const SUPABASE_URL = "https://cgqnlvtmrntqqzxwhnji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNncW5sdnRtcm50cXF6eHdobmppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDE1MjAsImV4cCI6MjA2ODE3NzUyMH0.DO7DlAnPxTk96b2hVb_GNQW5uSSgmU26xPwMOQxKbgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: AsyncStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});